In [3]:
import numpy as np
import pandas as pd

Considere os arrays numpy X, y abaixo:

In [16]:
from sklearn.datasets import load_iris

X = load_iris().data
y = load_iris().target

In [17]:
X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [22]:
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

__Exercício 1:__ Crie um dataframe df do pandas a partir de X, y.

Primeiro, concatene os arrays numpy. Na sequência transforme o array final para um dataframe. Altere o nome das colunas para 'X1', 'X2', 'X3', 'X4' e 'target'.

In [ ]:
data = np.c_[X,y]
data[:10]

In [35]:
DF1 = pd.DataFrame(data, columns = ["X1","X2","X3","X4","target"])

In [55]:
DF1[:10]


X1   X2   X3   X4  target
0  5.1  3.5  1.4  0.2     0.0
1  4.9  3.0  1.4  0.2     0.0
2  4.7  3.2  1.3  0.2     0.0
3  4.6  3.1  1.5  0.2     0.0
4  5.0  3.6  1.4  0.2     0.0
5  5.4  3.9  1.7  0.4     0.0
6  4.6  3.4  1.4  0.3     0.0
7  5.0  3.4  1.5  0.2     0.0
8  4.4  2.9  1.4  0.2     0.0
9  4.9  3.1  1.5  0.1     0.0

__Exercício 2:__ Usando o df criano no exercício 1, calcule qual a média da variável 'X2', para cada valor de target. Dica: Use a função groupby no dataframe df para resolver.

In [38]:
DF1.groupby(by="target").apply(lambda x: x.X2.mean())

target
0.0    3.428
1.0    2.770
2.0    2.974
dtype: float64

__Exercício 3:__ Construa um dicionário mapeando os valores:
        
        0 - 'A'
        
        1 - 'B'
        
        2 - 'C'
        
Usando a função map, crie uma coluna nova no dataframe df chamada 'target_2' com o mapeamento feito. Dica: Use a função map como visto em aula.

In [41]:
dic = {0:"A",1:"B",2:"C"}
dic

{0: 'A', 1: 'B', 2: 'C'}

In [45]:
target_2 = DF1.target.map(dic)
target_2

0      A
1      A
2      A
3      A
4      A
      ..
145    C
146    C
147    C
148    C
149    C
Name: target, Length: 150, dtype: object

In [56]:
DF2 = np.c_[DF1,target_2]
DF2[:10]


array([[5.1, 3.5, 1.4, 0.2, 0.0, 'A'],
       [4.9, 3.0, 1.4, 0.2, 0.0, 'A'],
       [4.7, 3.2, 1.3, 0.2, 0.0, 'A'],
       [4.6, 3.1, 1.5, 0.2, 0.0, 'A'],
       [5.0, 3.6, 1.4, 0.2, 0.0, 'A'],
       [5.4, 3.9, 1.7, 0.4, 0.0, 'A'],
       [4.6, 3.4, 1.4, 0.3, 0.0, 'A'],
       [5.0, 3.4, 1.5, 0.2, 0.0, 'A'],
       [4.4, 2.9, 1.4, 0.2, 0.0, 'A'],
       [4.9, 3.1, 1.5, 0.1, 0.0, 'A']], dtype=object)

In [62]:
DFF = pd.DataFrame(DF2, columns=["X1","X2","X3","X4","target","target_2"])
DFF

X1   X2   X3   X4 target target_2
0    5.1  3.5  1.4  0.2    0.0        A
1    4.9  3.0  1.4  0.2    0.0        A
2    4.7  3.2  1.3  0.2    0.0        A
3    4.6  3.1  1.5  0.2    0.0        A
4    5.0  3.6  1.4  0.2    0.0        A
..   ...  ...  ...  ...    ...      ...
145  6.7  3.0  5.2  2.3    2.0        C
146  6.3  2.5  5.0  1.9    2.0        C
147  6.5  3.0  5.2  2.0    2.0        C
148  6.2  3.4  5.4  2.3    2.0        C
149  5.9  3.0  5.1  1.8    2.0        C

[150 rows x 6 columns]

**Exercício 4:**

4.1: Filtre o dataframe df onde X1 é maior do que 6 ou target é diferente de 2 e chame-o de df1. Dica: usar os filtros e os operadores vistos em aula;

4.2: Filtre os primeiros 15 índices do dataframe df e chame-o de df2;

4.3: Transformando os dataframes df1 e df2 para arrays. Multiplique df1 pelo transposto de df2 (use a função que calcula transposta de matriz) e printe o resultado final. Lembre-se de dropar a coluna target_2 de cada um dos dataframes antes de fazer a mutliplicação.

In [69]:
DFF1 = DFF[(DFF.X1 > 6) | (DFF.target != 2)]
DFF1

X1   X2   X3   X4 target target_2
0    5.1  3.5  1.4  0.2    0.0        A
1    4.9  3.0  1.4  0.2    0.0        A
2    4.7  3.2  1.3  0.2    0.0        A
3    4.6  3.1  1.5  0.2    0.0        A
4    5.0  3.6  1.4  0.2    0.0        A
..   ...  ...  ...  ...    ...      ...
144  6.7  3.3  5.7  2.5    2.0        C
145  6.7  3.0  5.2  2.3    2.0        C
146  6.3  2.5  5.0  1.9    2.0        C
147  6.5  3.0  5.2  2.0    2.0        C
148  6.2  3.4  5.4  2.3    2.0        C

[141 rows x 6 columns]

In [70]:
DFF2 = DFF1[:15]
DFF2

X1   X2   X3   X4 target target_2
0   5.1  3.5  1.4  0.2    0.0        A
1   4.9  3.0  1.4  0.2    0.0        A
2   4.7  3.2  1.3  0.2    0.0        A
3   4.6  3.1  1.5  0.2    0.0        A
4   5.0  3.6  1.4  0.2    0.0        A
5   5.4  3.9  1.7  0.4    0.0        A
6   4.6  3.4  1.4  0.3    0.0        A
7   5.0  3.4  1.5  0.2    0.0        A
8   4.4  2.9  1.4  0.2    0.0        A
9   4.9  3.1  1.5  0.1    0.0        A
10  5.4  3.7  1.5  0.2    0.0        A
11  4.8  3.4  1.6  0.2    0.0        A
12  4.8  3.0  1.4  0.1    0.0        A
13  4.3  3.0  1.1  0.1    0.0        A
14  5.8  4.0  1.2  0.2    0.0        A

In [79]:
F1 = DFF1.drop(["target_2"],axis=1)
F2 = DFF2.drop(["target_2"],axis=1)

In [83]:
F1 = np.array(F1)
F2 = np.array(F2)

In [86]:
resultado_final = np.dot(F1,F2.T)
resultado_final

array([[40.26, 37.489999999999995, 37.03, ..., 36.96, 33.989999999999995,
        45.3],
       [37.489999999999995, 35.010000000000005, 34.49, ..., 34.5, 31.63,
        42.14],
       [37.03, 34.49, 34.06, ..., 34.0, 31.26, 41.660000000000004],
       ...,
       [48.26, 45.75000000000001, 44.49, ..., 44.92999999999999, 40.28,
        52.92],
       [51.33, 48.53, 47.31, ..., 47.68000000000001, 42.870000000000005,
        56.339999999999996],
       [51.54, 48.6, 47.50000000000001, ..., 47.74999999999999,
        43.029999999999994, 56.50000000000001]], dtype=object)

__Exercício 5:__ 
    
5.1: Crie uma função que receba um  número inteiro positivo N e retorne um array 0, 1, ..., N. Dica: Use as funções que vimos para criação de arrays;
    
5.2: Crie uma função que receba um array [0,1, .., N] e retorne o mesmo array, só que com os números em posições aleatórias. Dica: use a função que vimos em aula que faz escolhas aleatórias SEM reposição;

5.3: Crie uma função que receba um número inteiro positivo N. Essa função deve retornar um array de tamanho N, cujos valores são números inteiros entre 0 e N-1 e pode haver repetição desses números.

In [4]:
def numero_inteiro(x):
    vec = np.arange(x+1)
    return vec

def funcao_r_array(y):
    if type(y)==np.ndarray:
        vec = np.random.choice(y,size=y.shape,replace = False)
        return vec
    else:
        print("INSERIR SOMENTE ARRAY")

def funcao_nint(n):
    vec = np.random.randint(0,n-1,size = n)
    return vec

In [5]:
numero_inteiro(7)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
rr = np.array([1,2,3,4,5,6,7,8,9,10])
funcao_r_array(rr)

array([ 8,  2,  3,  6,  1,  7,  4,  9, 10,  5])

In [9]:
funcao_nint(8)

array([4, 1, 0, 5, 1, 1, 6, 0])

__Exercício 6:__ Construa uma função divide_dados:
        
        - recebe um array X de dimensões quaisquer (n,k) e um parâmetro p entre 0 e 1.
        - divide o array X em duas partes disjuntas de forma aleatória. Ou seja, crie dois novos arrays, X1 e X2,
        onde a dimensão de linhas de X1 somada com a dimensão de linhas de X2 deve ser igual a dimensão de linhas de X.
        - interpretando p como percentual, o tamanho de X1 deve ser p*100% do número de linhas de X; enquanto X2 deve ser o resto.
        - retorne esses dois arrays.
        
       

In [11]:
def divide_dados(matriz,p):
    valor = matriz
    np.random.shuffle(valor)
    maximo = int(len(matriz)*p)
    X1 = valor[:maximo]
    X2 = valor[maximo:]
    return X1,X2
    

In [12]:
M = np.array([[2,6,2,4,5,6],[5,4,5,4,5,1]])
len(M)

2

In [15]:
X1, X2 = divide_dados(M,0.8)
print(M.shape,X1.shape,X2.shape)

(2, 6) (1, 6) (1, 6)


In [16]:
X1,X2

(array([[5, 4, 5, 4, 5, 1]]), array([[2, 6, 2, 4, 5, 6]]))